---
topics:
  velocity: /fix_velocity
  position: /ground_truth_to_tf/pose
  applicationStart: start
  applicationStop: stop
  sonar: /sonar_height
  barometer: /pressure_height
  simulator: /gazebo/model_states
  gps: /fix
      
simulatorbashpath: /home/ben/rosjava/src/drone/subb/src/main/java/bashFiles/startGazebo.sh
applicationbashpath: /home/ben/rosjava/src/drone/subb/src/main/java/bashFiles/startApp.sh
timeout: 50